#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

export PROJECT_ROOT="${PROJECT_ROOT:-$SCRIPT_DIR}"
export VALIDATION_RESULTS_ROOT="${VALIDATION_RESULTS_ROOT:-$REPO_ROOT}"
export REALWORLD_OUT_ROOT="${REALWORLD_OUT_ROOT:-$REPO_ROOT/GA_Results}"

export EXTERNAL_RUN_LABEL="${EXTERNAL_RUN_LABEL:-06_realworld_external_battery_40datasets}"
export EXTERNAL_TARGET_LOADED="${EXTERNAL_TARGET_LOADED:-120}"
export EXTERNAL_CSV_MAX_ROWS="${EXTERNAL_CSV_MAX_ROWS:-5000}"
export EXTERNAL_R="${EXTERNAL_R:-500}"
export EXTERNAL_BOOT_B="${EXTERNAL_BOOT_B:-500}"
export EXTERNAL_BOOT_B_EXTRA="${EXTERNAL_BOOT_B_EXTRA:-500}"
export EXTERNAL_BOOT_B_MAX="${EXTERNAL_BOOT_B_MAX:-1500}"
export EXTERNAL_TARGETED_EXTRA_R="${EXTERNAL_TARGETED_EXTRA_R:-300}"
export EXTERNAL_PROFILE_GATE="${EXTERNAL_PROFILE_GATE:-TRUE}"
export EXTERNAL_KEEP_NEGATIVE_CONTROLS="${EXTERNAL_KEEP_NEGATIVE_CONTROLS:-FALSE}"
export EXTERNAL_BENCHMARK_POLICY="${EXTERNAL_BENCHMARK_POLICY:-profile_preregistered}"
export EXTERNAL_WRITE_ORACLE_AUDIT="${EXTERNAL_WRITE_ORACLE_AUDIT:-TRUE}"
export EXTERNAL_SOURCE_CAP_PROP="${EXTERNAL_SOURCE_CAP_PROP:-0.25}"
export EXTERNAL_WINS_SATURATION_CAP="${EXTERNAL_WINS_SATURATION_CAP:-10}"
export EXTERNAL_ENABLE_FUTILITY_STOP="${EXTERNAL_ENABLE_FUTILITY_STOP:-TRUE}"
export EXTERNAL_FUTILITY_MIN_GATE_ROWS="${EXTERNAL_FUTILITY_MIN_GATE_ROWS:-12}"
export EXTERNAL_ENABLE_DEPTH_PROBE="${EXTERNAL_ENABLE_DEPTH_PROBE:-TRUE}"
export EXTERNAL_DEPTH_TRIGGER_WINS="${EXTERNAL_DEPTH_TRIGGER_WINS:-3}"
export EXTERNAL_DEPTH_MAX_VARIANTS="${EXTERNAL_DEPTH_MAX_VARIANTS:-3}"
export EXTERNAL_DEPTH_SAMPLE_FRAC="${EXTERNAL_DEPTH_SAMPLE_FRAC:-1.0}"
export EXTERNAL_FDR_ALPHA_PRIMARY="${EXTERNAL_FDR_ALPHA_PRIMARY:-0.05}"
export EXTERNAL_FDR_ALPHA_SECONDARY="${EXTERNAL_FDR_ALPHA_SECONDARY:-0.10}"
export EXTERNAL_GENERATE_PDF_REPORT="${EXTERNAL_GENERATE_PDF_REPORT:-TRUE}"
export EXTERNAL_CLEAN_OUTPUT_LAYOUT="${EXTERNAL_CLEAN_OUTPUT_LAYOUT:-TRUE}"

cd "$SCRIPT_DIR"
Rscript 13_realworld_external_battery.R
